[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
[[redirects]]
  from = "/s-base"
  to = "/index.html"
  status = 200
  force = true
[[redirects]]
  from = "/r-base"
  to = "/index.html"
  status = 200
  force = true
[[redirects]]
  from = "/mix"
  to = "/index.html"
  status = 200
  force = true